<?php

namespace CodingAvenue\LabadoSystemBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;
use CodingAvenue\LabadoSystemBundle\Document\User;
use CodingAvenue\LabadoSystemBundle\Document\Booking;

/**
 * BookingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookingRepository extends DocumentRepository
{
    public function findOneCurrent(User $user)
    {
        $book = $this->createQueryBuilder(Booking::class)
            ->field('user')->references($user)
            ->field('status')->equals(Booking::STATUS_IN_PROGRESS)
            ->getQuery()
            ->execute()
            ->getSingleResult();

        return $book;
    }
}