<?php

namespace CodingAvenue\LabadoSystemBundle\Repository;

/**
 * LabadoerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LabadoerRepository extends \Doctrine\ORM\EntityRepository
{
}
