<?php

namespace CodingAvenue\LabadoBundle\Repository;

/**
 * LaundryServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LaundryServiceRepository extends \Doctrine\ORM\EntityRepository
{
}
