<?php

namespace CodingAvenue\LabadoBundle\Repository;

/**
 * LaundryShopRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LaundryShopRepository extends \Doctrine\ORM\EntityRepository
{
}
