<?php

namespace CodingAvenue\LabadoBundle\Repository;

/**
 * LaundryServicesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LaundryServicesRepository extends \Doctrine\ORM\EntityRepository
{
}
